# container: "docker://condaforge/mambaforge:4.14.0-0"


rule all:
    input:
        expand(
            "01_READ_PREPROCESSING/03_kneaddata/{sample}_paired_1.fastq.gz",
            sample=["oral_unenriched"],
        ),


# Clumpify
rule clumpify:
    input:
        r1="/Users/hhayden-admin/Desktop/hhayden01_GitHub/SnakeMakeTest/{sample}_1.fastq.gz",
        r2="/Users/hhayden-admin/Desktop/hhayden01_GitHub/SnakeMakeTest/{sample}_2.fastq.gz",
    output:
        r1="01_READ_PREPROCESSING/02_CLUMPIFY/{sample}.1.fastq",
        r2="01_READ_PREPROCESSING/02_CLUMPIFY/{sample}.2.fastq",
    log:
        "00_LOGS/01_clumpify.{sample}.log",
    params:
        r1="/Users/hhayden-admin/Desktop/hhayden01_GitHub/SnakeMakeTest/{sample}_1.fastq",
        r2="/Users/hhayden-admin/Desktop/hhayden01_GitHub/SnakeMakeTest/{sample}_2.fastq",
    conda:
        "bbmap_39.00.yml"
    shell:
        """
        #unzip input files
        gunzip -f {input.r1}
        gunzip -f {input.r2}

        #run clumpify
        clumpify.sh \
        in={params.r1} \
        in2={params.r2} \
        out={output.r1} \
        out2={output.r2} \
        dedupe=t optical=t spany=t adjacent=t > {log} 2>&1
        """


# Download KneadData
rule Download_KneadData:
    output:
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.1.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.2.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.3.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.4.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.rev.1.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.rev.2.bt2",
    log:
        "00_LOGS/01_download_kneaddata.log",
    params:
        kneaddata_db="/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/",
    conda:
        "kneaddata_0.10.0.yml"
    shell:
        """
        #downlaod human genome reference to desired directory
        kneaddata_database --download human_genome bowtie2 {params.kneaddata_db}
        """


# KneadData
rule KneadData:
    input:
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.1.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.2.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.3.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.4.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.rev.1.bt2",
        "/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/hg37dec_v0.1.rev.2.bt2",
        r1="01_READ_PREPROCESSING/02_CLUMPIFY/{sample}.1.fastq",
        r2="01_READ_PREPROCESSING/02_CLUMPIFY/{sample}.2.fastq",
    output:
        r1="01_READ_PREPROCESSING/03_kneaddata/{sample}_paired_1.fastq.gz",
        r2="01_READ_PREPROCESSING/03_kneaddata/{sample}_paired_2.fastq.gz",
    log:
        "00_LOGS/01_kneaddata.{sample}.log",
    params:
        out_dir="01_READ_PREPROCESSING/03_kneaddata/",
        kneaddata_db="/Users/hhayden-admin/Desktop/hhayden01_GitHub/Resources/",
        prefix="{sample}",
        r1="01_READ_PREPROCESSING/03_kneaddata/{sample}_paired_1.fastq",
        r2="01_READ_PREPROCESSING/03_kneaddata/{sample}_paired_2.fastq",
    conda:
        "kneaddata_0.10.0.yml"
    shell:
        """
        #run kneaddata to quality filter and remove host reads
        kneaddata --input {input.r1}  --input {input.r2} \
        --output {params.out_dir} \
        --output-prefix {params.prefix} \
        --reference-db {params.kneaddata_db} \
        --bypass-trf \
        --trimmomatic $CONDA_PREFIX/share/trimmomatic-0.39-2/ \
        --log {log}

        gzip {params.r1}
        gzip {params.r2}
        """
